# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ local ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: node ./build.js
    - name: Push
      uses: ad-m/github-push-action@v0.6.0
      with: 
        github_token: $\{{ secrets.TOKEN }}
