name: 同步到 Gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 同步到 Gitee
      - uses: actions/checkout@v2
      - run: git remote add gitee git@gitee.com:hanyeawa/confless.git
      - run: git add -A
      - run: git commit -m "从 Github 上同步"
      - run: git push gitee local
